services:
  chat:
    container_name: chat
    build: .
    ports:
      - "3029:3029"
    secrets:
      - redis_secret
    environment:
      NODE_ENV: development
    networks:
      - site
    restart: unless-stopped

secrets:
  redis_secret:
    file: ./secrets/redis_secret.txt

networks:
  site:
    external: true
